{
  imports = [
    ./auto-upgrade.nix
    ./boot.nix
    ./checkout-dotfiles.nix
    ./desktop.nix
    ./fonts.nix
    ./locale.nix
    ./networking.nix
    ./nix-settings.nix
    ./openssh.nix
    ./packages.nix
    ./programs.nix
    ./security.nix
    ./shell
    ./sound.nix
    ./unstable-overlay.nix
  ];
}
